#!/bin/bash
#SBATCH --image=docker:jderose/hdsims_stack:latest
#SBATCH -A mp107d
#SBATCH -C cpu
#SBATCH -q shared
#SBATCH -t 2:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH -o /pscratch/sd/x/xzackli/joboutput/%x.o%j
#SBATCH -J massconv
#SBATCH --mail-type=ALL
#SBATCH --mail-user=zackli@berkeley.edu
#SBATCH --array=0-10

cd /pscratch/sd/x/xzackli/hd/HalfDome-DataRelease
srun shifter python convert_masses.py $SLURM_ARRAY_TASK_ID
